branch-defaults:
  master:
    environment: image
global:
  application_name: image_searcher
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.4
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
