# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_auto_20170731_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='abs',
            field=models.CharField(default='anonimous', max_length=10),
            preserve_default=False,
        ),
    ]
