# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0004_image_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=255, unique=True)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image_path',
            new_name='image_name',
        ),
        migrations.RemoveField(
            model_name='image',
            name='abs',
        ),
        migrations.RemoveField(
            model_name='image',
            name='status',
        ),
        migrations.RemoveField(
            model_name='image',
            name='tags',
        ),
    ]
