# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0005_auto_20170801_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='model',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
