# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 07:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0006_auto_20170801_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='label_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image.Label'),
        ),
    ]
