# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 07:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0007_auto_20170801_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='label_name',
            new_name='label',
        ),
    ]
