# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0009_auto_20170803_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
