# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 04:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0010_label_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='file',
        ),
    ]
